// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbj_Szo2-ffJftRLmfVpaaTIW4B2-ienQ',
    appId: '1:1042379090777:web:3409c31016f1e1f60e7a48',
    messagingSenderId: '1042379090777',
    projectId: 'fluttermoviequotes',
    authDomain: 'fluttermoviequotes.firebaseapp.com',
    storageBucket: 'fluttermoviequotes.appspot.com',
    measurementId: 'G-ZWD540BRG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHrCzO5nOzaRI63v50usGNetQCV9WZAzM',
    appId: '1:1042379090777:android:3f60cc9d1906d6350e7a48',
    messagingSenderId: '1042379090777',
    projectId: 'fluttermoviequotes',
    storageBucket: 'fluttermoviequotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRp0wf76UN4gfTDyfEOsJnZXPDhmsAOyw',
    appId: '1:1042379090777:ios:938475214c46eb010e7a48',
    messagingSenderId: '1042379090777',
    projectId: 'fluttermoviequotes',
    storageBucket: 'fluttermoviequotes.appspot.com',
    iosClientId: '1042379090777-08rdd1chi4rm79ctqc0coqalocjs80do.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieQuotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRp0wf76UN4gfTDyfEOsJnZXPDhmsAOyw',
    appId: '1:1042379090777:ios:938475214c46eb010e7a48',
    messagingSenderId: '1042379090777',
    projectId: 'fluttermoviequotes',
    storageBucket: 'fluttermoviequotes.appspot.com',
    iosClientId: '1042379090777-08rdd1chi4rm79ctqc0coqalocjs80do.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieQuotes',
  );
}
